# Generated by Django 4.2 on 2023-09-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
